# Generated by Django 5.1.1 on 2024-09-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wing_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('JPY', 'JPY')], default='USD', max_length=100)),
                ('amount_as_per_agreement_currency', models.FloatField()),
                ('amount_in_equivalent_million_us', models.FloatField()),
                ('date_of_signature', models.DateTimeField(auto_now_add=True)),
                ('development_partner', models.CharField(max_length=100)),
                ('loan_or_grant', models.CharField(choices=[('Loan', 'Loan')], default='Loan', max_length=200)),
                ('sector', models.CharField(choices=[('General Public Services', 'General Public Services'), ('Defence', 'Defence'), ('Public Order and Safety', 'Public Order and Safety'), ('Industrial and Economic Services', 'Industrial and Economic Services'), ('Agriculture', 'Agriculture'), ('Power and Energy', 'Power and Energy'), ('Transport and Communications', 'Transport and Communications'), ('Local Government and Rural Development', 'Local Government and Rural Development'), ('Environment, Climate Change (CC) and Water Resources (WR)', 'Environment, Climate Change (CC) and Water Resources (WR)'), ('Housing and Community Amenities', 'Housing and Community Amenities'), ('Health', 'Health'), ('Recreation, Culture and Religion', 'Recreation, Culture and Religion'), ('Education', 'Education'), ('Science and IT', 'Science and IT'), ('Social Protection', 'Social Protection')], default='General Public Services', max_length=500)),
                ('comments', models.TextField()),
            ],
        ),
    ]
