# Generated by Django 5.1.1 on 2024-09-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wing_one',
            name='loan_or_grant',
            field=models.CharField(choices=[('Loan', 'Loan'), ('Grant', 'Grant')], default='Loan', max_length=200),
        ),
    ]
