# Generated by Django 5.1.1 on 2024-10-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wing', '0006_alter_wing_one_date_of_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO_FINANCER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ADB', 'ADB'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('AIIB', 'AIIB'), ('Belgium', 'Belgium'), ('Bulgaria', 'Bulgaria'), ('Belarus', 'Belarus'), ('Canada/CIDA', 'Canada/CIDA'), ('Canada/CIDA', 'Canada/CIDA'), ('China', 'China'), ('Czechoslovakia', 'Czechoslovakia'), ('Denmark', 'Denmark'), ('EU/EEC', 'EU/EEC'), ('EIB', 'EIB'), ('FAO', 'FAO'), ('French/AFD', 'French/AFD'), ('GAVI', 'GAVI'), ('GAIN', 'GAIN'), ('GEF', 'GEF'), ('Germany/(GIZ/KFW)', 'Germany/(GIZ/KFW)'), ('GFATM', 'GFATM'), ('Hungary', 'Hungary'), ('IBRD', 'IBRD'), ('IDA', 'IDA'), ('IFAD', 'IFAD'), ('IMO', 'IMO'), ('ILO', 'ILO'), ('India', 'India'), ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('IDB', 'IDB'), ('Italy', 'Italy'), ('Japan/JICA', 'Japan/JICA'), ('Kuwait', 'Kuwait'), ('NDF', 'NDF'), ('Netherland', 'Netherland'), ('Norway', 'Norway'), ('North Korea', 'North Korea'), ('OPEC', 'OPEC'), ('Pakistan', 'Pakistan'), ('Poland', 'Poland'), ('Romania', 'Romania'), ('Russia', 'Russia'), ('Rockefeller', 'Rockefeller'), ('Saudi Arabia/SFD', 'Saudi Arabia/SFD'), ('South Korea/KOICA', 'South Korea/KOICA'), ('Spain', 'Spain'), ('Sweden', 'Sweden'), ('Switzerland/SDC/SIDA', 'Switzerland/SDC/SIDA'), ('Singapore', 'Singapore'), ('SAARC Dev. Fund (SDF)', 'SAARC Dev. Fund (SDF)'), ('UNOPS', 'UNOPS'), ('UNEF', 'UNEF'), ('The Union ', 'The Union '), ('UAE', 'UAE'), ('UNDP', 'UNDP'), ('UNIDO', 'UNIDO'), ('UNFPA', 'UNFPA'), ('UNICEF', 'UNICEF'), ('UNESCO', 'UNESCO'), ('UK/DFID', 'UK/DFID'), ('USA/USAID', 'USA/USAID'), ('UNEP', 'UNEP'), ('WFP', 'WFP'), ('WHO', 'WHO'), ('UN Woman', 'UN Woman'), ('Yugoslavia', 'Yugoslavia'), ('UNCDF', 'UNCDF')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='wing_one',
            name='co_financer',
        ),
        migrations.AlterField(
            model_name='wing_one',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('JPY', 'JPY'), ('A $', 'A $'), ('AS', 'AS'), ('BF', 'BF'), ('BSTC', 'BSTC'), ('C $', 'C $'), ('DFL', 'DFL'), ('Dirham', 'Dirham'), ('DKR', 'DKR'), ('DM', 'DM'), ('Euro', 'Euro'), ('FF', 'FF'), ('FM', 'FM'), ('ID', 'ID'), ('IDR', 'IDR'), ('IRS', 'IRS'), ('KD', 'KD'), ('Lira', 'Lira'), ('NKR', 'NKR'), ('NZD', 'NZD'), ('Rbl', 'Rbl'), ('SDR', 'SDR'), ('CHF/SF', 'CHF/SF'), ('SKR', 'SKR'), ('SR', 'SR'), ('STG/GBP', 'STG/GBP'), ('Taka', 'Taka'), ('Yen', 'Yen'), ('Yuan', 'Yuan'), ('Won', 'Won')], default='USD', max_length=100),
        ),
        migrations.AddField(
            model_name='wing_one',
            name='co_financer',
            field=models.ManyToManyField(to='Wing.co_financer'),
        ),
    ]
