# Generated by Django 5.1.1 on 2024-10-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wing', '0009_wing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000, null=True)),
            ],
        ),
    ]
