# Generated by Django 5.1.1 on 2024-10-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wing', '0010_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wing',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
