# Generated by Django 5.1.1 on 2024-10-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wing', '0012_wing_one_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wing_one',
            name='author',
        ),
        migrations.AddField(
            model_name='wing_one',
            name='current_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wing_one',
            name='if_loan_conditionally',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wing_one',
            name='previous_status',
            field=models.TextField(null=True),
        ),
    ]
