# Generated by Django 5.1.1 on 2024-10-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wing', '0013_remove_wing_one_author_wing_one_current_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wing_one',
            old_name='previous_status',
            new_name='previous_month_status',
        ),
    ]
