# Generated by Django 5.1.1 on 2024-10-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wing', '0014_rename_previous_status_wing_one_previous_month_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wing_one',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wing_one',
            name='current_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wing_one',
            name='if_loan_conditionally',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wing_one',
            name='previous_month_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
