# Generated by Django 5.1.1 on 2024-10-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wing', '0015_alter_wing_one_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wing_one',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
